### ISSUE TITLE
Dio error - Not getting the env variables (ApiKey and Base URL)

### ISSUE THREAD

**Issue by vnl** [Iamzaryab/Movie-Application-Flutter-Clean-Architecture#2]
It's a great-looking app, and using Riverpod is amazing. 

I tried to follow the instructions and added the .env file in the project's root. However, I get the following dio errors. 
```
flutter: *** DioException ***:
flutter: uri: movie/now_playing?page=1&api_key=
flutter: DioException [unknown]: null
Error: Invalid argument(s): No host specified in URI movie/now_playing?page=1&api_key=
```
I even tried making a copy of the .env file in the lib folder, but that did not work. (I promise to try and debug this, but I thought it's best to let you know, too). 

One more thing I noticed: app_env.dart is an empty file. 
<img width="1459" alt="image" src="https://github.com/Iamzaryab/Movie-Application-Flutter-Clean-Architecture-RiverPod/assets/1355466/efd2d91f-b4da-4173-be94-e131dcd009a4">

**Comment by vnl** [comment]
A dirty hack (I don't think that is what you intended) I tried is in the file dio_network_service.dart 
```
@override
  String get baseUrl =>
      dotenv.env[NetworkEnv.BASE_URL.name] ?? 'https://api.themoviedb.org/3/';

  @override
  String get apiKey =>
      dotenv.env[NetworkEnv.API_KEY.name] ?? 'myApiKey';
```

**Comment by Iamzaryab** [comment]
Hi @vnl please refer to https://github.com/Iamzaryab/Movie-Application-Flutter-Clean-Architecture-RiverPod#getting-started
so basically steps are simple 
1.Create a .env file in root directory
2.https://www.themoviedb.org/settings/api create an API from this website 
3. BASE_URL=https://api.themoviedb.org/3/
4.API_KEY=PASTE_YOUR_API_KEY
that's it project will start working as expected

**Comment by vnl** [comment]
@Iamzaryab, sorry, I think I did not communicate it properly. If you see the first post, I have the .env file in the root with the BASE_URL and API_KEY. 
Only for the screenshot I change the API key, of course. With that in place, it does not work. 

Have I missed something?

**Comment by Iamzaryab** [comment]
@vnl did you tried to run 
flutter pub run build_runner build --delete-conflicting-outputs 
is it still not working ?

**Comment by Iamzaryab** [comment]
@vnl i checked again on my side code is working fine If you have still facing an issue I can check your code or you can contact me my LinkedIn https://www.linkedin.com/in/zaryab-shakir-035b58171/

**Comment by vnl** [comment]
> @vnl did you tried to run flutter pub run build_runner build --delete-conflicting-outputs is it still not working ?

I did this @Iamzaryab 

I followed the instructions exactly:
Git cloned, created a new .env file and added the 2 variables, flutter pub get to get dependencies and finally ran the command "flutter pub run build_runner build --delete-conflicting-outputs" 
I get the above error. So there is no code change I promise.

**Comment by vnl** [comment]
@Iamzaryab I am sorry this is an oversight from me. I was able to solve it. As I mentioned, I followed your instructions a little too well. 
I had (from the screenshots you can see), named my variables from the instructions:
```
BASEURL=https://api.themoviedb.org/3/
APIKEY=ADD YOUR API KEY
```

However, the variables you are loading using dotenv is BASE_URL and API_KEY - the underscore was the issue :) COuld you change that in the read, please?
