### ISSUE TITLE
Movie Details screen does not come up - Exception

### ISSUE THREAD

**Issue by vnl** [Iamzaryab/Movie-Application-Flutter-Clean-Architecture#3]
Sorry about this, another issue I found. 
So, the Home Page loads now with me explicitly providing the API key and URL. However, now clicking on a movie crashes with the following exception. 
`HttpExceptionWithStatus (HttpException: Invalid statusCode: 404, uri = https://image.tmdb.org/t/p/w780)`
I am assuming it is not passing the movie id. 
`HttpExceptionWithStatus (HttpException: Invalid statusCode: 404, uri = https://image.tmdb.org/t/p/w780)`

<img width="1209" alt="image" src="https://github.com/Iamzaryab/Movie-Application-Flutter-Clean-Architecture-RiverPod/assets/1355466/77d4f811-ce57-46d9-93c5-7063e8af0d1a">
<img width="1324" alt="image" src="https://github.com/Iamzaryab/Movie-Application-Flutter-Clean-Architecture-RiverPod/assets/1355466/01f0156f-0835-45f8-a919-29475208ff16">

**Comment by Iamzaryab** [comment]
hi @vnl no problem at all, we all learn with this. 
statically passing the API_KEY and baseurl won't solve you have to properly init the application
please refer to https://github.com/Iamzaryab/Movie-Application-Flutter-Clean-Architecture-RiverPod#getting-started
so basically steps are simple
1.Create a .env file in root directory
2.https://www.themoviedb.org/settings/api create an API from this website
3. BASE_URL=https://api.themoviedb.org/3/
4.API_KEY=PASTE_YOUR_API_KEY
that's it project will start working as expected

**Comment by Iamzaryab** [comment]
if you still find any issue please let me know

**Comment by vnl** [comment]
So, after sorting out the [other issue](https://github.com/Iamzaryab/Movie-Application-Flutter-Clean-Architecture-RiverPod/issues/2#issuecomment-1732636265) I still get this issue. 
I think it is trying to load pictures which are not there from the API.

**Comment by vnl** [comment]
Thank you for helping out. It turns out that if I had used Android Studio and just run the app instead of debugging, it would work straight away. 
Thanks again @Iamzaryab I appreciate you spending time and explaining that.

**Comment by Iamzaryab** [comment]
No problem at all! I'm really pleased to hear that app is working now. If you ever have more questions or need help with anything else, just let me know.
